### ISSUE TITLE
[[3.1][3.2][DEV] MegaMenu, Sticky Menu, Navbar for phpBB] probl de modification de menu déjà

### ISSUE THREAD

**Issue by Sets71** [orthohincom/phpbb-navbar#2]
Hello,
Thx you for this extension!!
I have a small problem and one question please :) 
My problem is: when i try to edit a menu already created ( change the name or add a link ) i have an error like this:
`
[code]Erreur générale
SQL ERROR [ mysqli ]

Incorrect integer value: '' for column 'is_mega' at row 1 [1366]

SQL

UPDATE phpbb_orthohin_navbar_menu SET button_url = '', button_name = 'Energies', button_desc = '', button_external = 0, button_display = 1, button_only_registered = 0, button_only_guest = 0, parent_id = 16, is_mega = '', icon = '' WHERE button_id = 28

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/orthohin/navbar/acp/orthohin_navbar_module.php
LINE: 442
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: orthohin\navbar\acp\orthohin_navbar_module->main()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()
`

Do you have an idea to resolve it please?

and my question is : how to delete the logo name on the left of "Home"? or load my logo via APC because when i log my logo i have another error: 
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/orthohin/navbar/acp/orthohin_navbar_module.php on line 86: move_uploaded_file(./../ext/orthohin/navbar/images/logo/site_logo.gif): failed to open stream: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/ext/orthohin/navbar/acp/orthohin_navbar_module.php on line 86: move_uploaded_file(): Unable to move '/tmp/phppkA04q' to './../ext/orthohin/navbar/images/logo/site_logo.gif'

Warning: Cannot modify header information - headers already sent by (output started at /homepages/24/d632201818/htdocs/includes/functions.php:3262) in /homepages/24/d632201818/htdocs/includes/functions_acp.php on line 137

Warning: Cannot modify header information - headers already sent by (output started at /homepages/24/d632201818/htdocs/includes/functions.php:3262) in /homepages/24/d632201818/htdocs/includes/functions_acp.php on line 137

Warning: Cannot modify header information - headers already sent by (output started at /homepages/24/d632201818/htdocs/includes/functions.php:3262) in /homepages/24/d632201818/htdocs/includes/functions_acp.php on line 137`

Thx you very much!

**Comment by orthohincom** [comment]
This issue should be solved now.
Please download again from github and replace all files.
